### ISSUE TITLE
@oas-tools/commons 1.0.1 typings broken

### ISSUE THREAD

**Issue by pebo** [oas-tools/oas-devtools#10] opened 2023-03-01 18:39 UTC
## **Describe the bug**
The content of `index.d.ts` is broken in the @oas-tools/commons v1.0.1 module:

````
node_modules/@oas-tools/commons/dist/index.d.ts
export * from "./middleware/index.js";
export * from "./utils/index.js";
export CHANGELOG.md LICENSE README.md dist node_modules package-lock.json package.json schemas src tsconfig.json typings from ../typings
````

The last line should not be there. The line was likely added by the build target in `package.json` which seem to include some early work on typescript migration:

````
    "build": "tsc && cp src/index.mjs dist/index.mjs && echo export * from '../typings' >> dist/index.d.ts",
````

## **To Reproduce**

`yarn build`

Errors:
````
../../node_modules/@oas-tools/commons/dist/index.d.ts:3:1 - error TS1128: Declaration or statement expected.

3 export CHANGELOG.md LICENSE README.md dist node_modules package-lock.json package.json schemas src tsconfig.json typings from ../typings

...etc
````

## **Expected behavior**
No extract lines in `index.d.ts`.

## **Screenshots**
n/a

## **Desktop (please complete the following information):**
n/a

## **Smartphone (please complete the following information):**
n/a

**Comment by alesancor1** [comment] 2023-03-02 01:12
That line adds the custom typings at `typings` directory to the typings file generated by `tsc`, it is an important line because it defines types for the middleware classes and OpenAPI docs. 

I think the problem is that `export` is a reserved work for some terminals (like bash) and when doing `export * from ../typings` it is generating all the directories at `../` as text. The line that should be added at the end of `index.d.ts` is `export * from '../typings'`. If we added quotes to that line in the build npm command it should work:

```json
{
   "build": "tsc && cp src/index.mjs dist/index.mjs && echo \"export * from '../typings'\" >> dist/index.d.ts"
}
```

**Comment by pebo** [comment] 2023-03-02 07:53
v1.0.0 has this `index.d.ts` (with is the same content as `/typings/index.d.ts` in the repo).

```
export * from './middleware';
export * from './openapi';
```

The types from both middleware and openapi are already re-exported from the index.d.ts file? Not sure what effect adding `export * from '../typings'` has.

**Comment by alesancor1** [comment] 2023-03-02 14:46
When `tsc` runs it creates the `dist` directory, which contains the main `index.d.ts` file that exports automatically generated typings. Apart from those typings generated by tsc, it is necessary to export the custom types defined at `/typings/index.d.ts`, so they can be imported by other modules, that's why we have that line added at the end of `/dist/index.d.ts` file.

**Comment by pebo** [comment] 2023-03-03 07:01
PR https://github.com/oas-tools/oas-commons/pull/11 updated to generate valid `/dist/index.d.ts`file:

Content after change:
`````js

export * from "./middleware/index.js";
export * from "./utils/index.js";
export * from "../typings";
`````

**Comment by alesancor1** [comment] 2023-03-04 00:02
@pebo I just tested the changes at #11 and it generated a wrong `/dist/index.d.ts`:
```javascript
export * from "./middleware/index.js";
export * from "./utils/index.js";
"export * from \"../typings\";" 
```

Also, this does not affect the modules using the library, since it is built by the CI/CD without problems and then published in the npm registry. By the description you gave me above, it only happens when running `npm run build` manually in certain terminals.

Anyways, check if this command works for you, I changed `echo` to `printf` and escaped quotes:
```json
{
    "build":  "tsc && cp src/index.mjs dist/index.mjs && printf 'export * from \"../typings\";' >> dist/index.d.ts",
}
```

If that doesn't work either, I'm closing this issue since it doesn't affect other modules.

**Comment by pebo** [comment] 2023-03-04 08:42
@alesancor1 the updated command with `printf` works fine and the PR is now adjusted - thanks. I tested `npm run build` with zsh 5.8 and bash 3.2 and the file seems to be correctly generated in both shells.

As far as I can tell the package distribution in the npm registry contains the wrong export line in `dist/index.d.ts`:

````sh
curl --output commons-1.0.1.tgz https://registry.npmjs.org/@oas-tools/commons/-/commons-1.0.1.tgz
tar xzf commons-1.0.1.tgz
cat package/dist/index.d.ts 
export * from "./middleware/index.js";
export * from "./utils/index.js";
export CHANGELOG.md LICENSE README.md dist node_modules package-lock.json package.json schemas src tsconfig.json typings from ../typing
````

**Comment by alesancor1** [comment] 2023-03-04 11:19
Yep, I just checked it, too. I'm merging the PR and it should fix that bug, thanks :)

**Closed as completed** 2023-03-07 00:45 UTC
Labels: bug
